# Generated by Django 6.0 on 2025-12-09 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(default=1, help_text='Select a language for this book', on_delete=django.db.models.deletion.RESTRICT, to='catalog.language'),
        ),
    ]
