# Generated by Django 6.0 on 2026-01-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_bookinstance_language_book_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_photo',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_photo',
        ),
    ]
