# Generated by Django 6.0 on 2026-01-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_author_author_photo_remove_book_book_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_photo',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_photo',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
    ]
