# Generated by Django 6.0 on 2026-01-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_author_author_photo_book_book_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_photo',
            new_name='photo',
        ),
    ]
