# Generated by Django 6.0 on 2026-01-09 22:30

from locallibrary.utils.image_proccess import GeneratePath
from locallibrary.utils.validators import validate_file_size
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_author_photo_author_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=GeneratePath('authors'), validators=[validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'webp', 'jpg', 'svg'], message='Invalid file extension')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=GeneratePath('book'), validators=[validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'webp', 'jpg', 'svg'], message='Invalid file extension')]),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, help_text='Date when book should become available', null=True),
        ),
    ]
