# Generated by Django 6.0 on 2026-01-09 22:30

import common.file.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_author_photo_author_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=common.file.utils.GeneratePath('authors'), validators=[common.file.utils.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'webp', 'jpg', 'svg'], message='Invalid file extension')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=common.file.utils.GeneratePath('book'), validators=[common.file.utils.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'webp', 'jpg', 'svg'], message='Invalid file extension')]),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, help_text='Date when book should become available', null=True),
        ),
    ]
