# Generated by Django 6.0 on 2026-01-17 12:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_author_photo_alter_book_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('issued_at', models.DateField(auto_now_add=True)),
                ('due_back', models.DateField()),
                ('returned_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('a', 'Active'), ('r', 'Returned')], default='a', max_length=20)),
                ('is_overdue', models.BooleanField(blank=True, null=True)),
                ('overdue_days', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(default=1, help_text='Select a language for this book', on_delete=django.db.models.deletion.PROTECT, to='catalog.language'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.book'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='bookinstance',
            index=models.Index(fields=['borrower', 'status', 'book'], name='catalog_boo_borrowe_e0a571_idx'),
        ),
        migrations.AddField(
            model_name='loan',
            name='book_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='catalog.bookinstance'),
        ),
        migrations.AddField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['borrower', 'status'], name='catalog_loa_borrowe_51b71a_idx'),
        ),
    ]
