# Generated by Django 6.0.3 on 2026-03-25 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_loan_alter_book_author_alter_book_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_change_status', 'Set any book status'))},
        ),
        migrations.RemoveIndex(
            model_name='bookinstance',
            name='catalog_boo_borrowe_e0a571_idx',
        ),
        migrations.RemoveIndex(
            model_name='loan',
            name='catalog_loa_borrowe_51b71a_idx',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', related_name='books', to='catalog.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Select a language for this book', on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.language'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='catalog.book'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='borrowed_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book availability', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bookinstance',
            index=models.Index(fields=['borrower'], name='catalog_boo_borrowe_40f5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinstance',
            index=models.Index(fields=['book'], name='catalog_boo_book_id_917dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['borrower'], name='catalog_loa_borrowe_137612_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookinstance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['o', 'r']), _negated=True), models.Q(('due_back__isnull', False), ('borrower__isnull', False)), _connector='OR'), name='check_due_back_and_borrower_if_on_loan_or_reserved', violation_error_message='Due back date and borrower cannot be empty when book is on loan or reserved.'),
        ),
        migrations.RemoveField(
            model_name='loan',
            name='due_back',
        ),
    ]
