# Generated by Django 6.0.3 on 2026-04-05 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_bookinstance_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='photo',
            new_name='image',
        ),
    ]
