# Generated by Django 6.0.3 on 2026-05-22 21:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rename_photo_author_image_rename_photo_book_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_change_due_back', 'Set due back date'), ('can_change_status', 'Can change book status'))},
        ),
        migrations.RemoveField(
            model_name='loan',
            name='is_overdue',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='overdue_days',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='catalog.book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['book_instance', 'returned_at'], name='catalog_loa_book_in_0b469e_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['borrower', 'returned_at'], name='catalog_loa_borrowe_3eed5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.CheckConstraint(condition=models.Q(('date_of_birth__isnull', True), ('date_of_death__isnull', True), ('date_of_birth__lte', models.F('date_of_death')), _connector='OR'), name='check_birth_before_death', violation_error_message='Author could not die earlier than was born!'),
        ),
    ]
