# Generated by Django 6.0 on 2026-01-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified_at',
        ),
    ]
