# Generated by Django 6.0 on 2026-01-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userprofile_email_verified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
