# Generated by Django 6.0 on 2026-01-09 22:30

from utils.image_proccess import GeneratePath
from utils.validators import validate_file_size
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=GeneratePath('users'), validators=[validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'webp', 'jpg', 'svg'], message='Invalid file extension')]),
        ),
    ]
