# Generated by Django 6.0.3 on 2026-03-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('customer', 'Customer')], default='customer', max_length=150),
        ),
    ]
