name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    env:
        ENGINE: django.db.backends.postgresql
        POSTGRES_DB: test_db
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_password
        POSTGRES_HOST: localhost 
        REDIS_URL_CACHE: redis://localhost:6379/0
        CELERY_BROKER_URL: redis://localhost:6379/0
        CELERY_RESULT_BACKEND: redis://localhost:6379/0
        SECRET_KEY: "dummy-key-for-tests"
        DEBUG: "True"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run Ruff Format Check
        run: uv run ruff format --check .

      - name: Run Ruff Linter
        run: uv run ruff check .

      - name: Run Mypy Type Checking
        run: uv run mypy locallibrary/

      - name: Run Bandit Security Scan
        run: uv run bandit -c pyproject.toml -r locallibrary/

      - name: Check Django Migrations
        run: uv run python locallibrary/manage.py makemigrations --check --dry-run

      - name: Run Tests with Pytest
        run: uv run pytest

  deploy:
      needs: check-and-test
      if: github.ref == 'refs/heads/master'
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to DigitalOcean
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.DO_HOST }}
            username: ${{ secrets.DO_USERNAME }}
            key: ${{ secrets.DO_SSH_KEY }}
            script: |
                        cd /opt/locallibrary
                        git pull origin master
                        
                        cat <<EOF > .env.prod
                        DEBUG=False
                        ENGINE=django.db.backends.postgresql
                        POSTGRES_HOST=prod_db
                        REDIS_URL_CACHE=redis://redis:6379/1
                        CELERY_BROKER_URL=redis://redis:6379/2
                        CELERY_RESULT_BACKEND=redis://redis:6379/3
                        
                        POSTGRES_DB=${{ vars.POSTGRES_DB }}
                        POSTGRES_USER=${{ vars.POSTGRES_USER }}
                        CLOUDFLARE_R2_BUCKET=${{ vars.CLOUDFLARE_R2_BUCKET }}
                        CLOUDFLARE_R2_BUCKET_ENDPOINT=${{ vars.CLOUDFLARE_R2_BUCKET_ENDPOINT }}
                        CLOUDFLARE_R2_DOMAIN=${{ vars.CLOUDFLARE_R2_DOMAIN }}
                        GOOGLE_CLIENT=${{ vars.GOOGLE_CLIENT }}
                        GITHUB_CLIENT=${{ vars.MY_GITHUB_CLIENT }}
                        EMAIL_HOST_USER=${{ vars.EMAIL_HOST_USER }}
                        SITE_URL=${{ vars.SITE_URL }}
                        ALLOWED_HOSTS=${{ vars.ALLOWED_HOSTS }}
                        CSRF_TRUSTED_ORIGINS=${{ vars.CSRF_TRUSTED_ORIGINS }}
                        
                        SECRET_KEY=${{ secrets.SECRET_KEY }}
                        POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
                        CLOUDFLARE_R2_ACCESS_KEY=${{ secrets.CLOUDFLARE_R2_ACCESS_KEY }}
                        CLOUDFLARE_R2_SECRET_KEY=${{ secrets.CLOUDFLARE_R2_SECRET_KEY }}
                        GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }}
                        GITHUB_SECRET=${{ secrets.MY_GITHUB_SECRET }}
                        EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}
                        EOF
                        
                        docker compose -f compose.prod.yaml up -d --build
              
                        docker compose -f compose.prod.yaml exec -T server python locallibrary/manage.py migrate
                        docker compose -f compose.prod.yaml exec -T server python locallibrary/manage.py collectstatic --noinput
